### ISSUE TITLE
Could not initialize project, Python 3.10+

### ISSUE THREAD

**Issue by imsakg** [platformio/platform-ststm32#608]
With Python3.10, they move Iterable object under Collections.**abc** So im getting error when i initialize project. Is will be fix for it or am i need to use Python3.9 ?

https://pastebin.com/raw/GiQ968XN

**Comment by zayats1** [comment]
same problem

**Comment by imsakg** [comment]
@zayats1
Hey, i fixed my problem with using platformio core. I also patch some package files because im using Python3.10+.
Changes:
+ /home/$USER/.platformio/packages/framework-mbed/platformio/package_deps/py3/past/types/oldstr.py
Line 5 :
+  from collections import Iterable >  from collections.abc import Iterable 

+ /home/$USER/.platformio/packages/framework-mbed/platformio/package_deps/py3/past/types/oldstr.py
Line 4:
+  from collections import Mapping > from collections.abc import Mapping

**Comment by zayats1** [comment]
@imsakg Thank you! It works.

**Comment by matteomeneghetti** [comment]
I have encountered this issue as well and the easy fix provided by @imsakg worked fine.
I suppose the python3 dependencies list should be updated to include the most recent _python-future_ package version (which contains the _past_ package as well), as shown for example [here](https://github.com/PythonCharmers/python-future/blob/master/src/past/types/oldstr.py) and [here](https://github.com/PythonCharmers/python-future/blob/master/src/past/builtins/misc.py)?

**Comment by mattj23** [comment]
Python 3.10 has been out for almost a year now, it's probably worth trying to get these fixes into the main release.  Is this the right repository for a fix?

**Comment by qleonardolp** [comment]
> @zayats1 Hey, i fixed my problem with using platformio core. I also patch some package files because im using Python3.10+. Changes: ~ /home/$USER/.platformio/packages/framework-mbed/platformio/package_deps/py3/past/types/oldstr.py Line 5 :
> 
>     * from collections import Iterable >  from collections.abc import Iterable
> 
> 
> ~ /home/$USER/.platformio/packages/framework-mbed/platformio/package_deps/py3/past/builtins/misc.py Line 4:
> 
>     * from collections import Mapping > from collections.abc import Mapping

After these steps is it necessary any other configuration? I edited the files, however the problem persists

**Comment by imsakg** [comment]
> > @zayats1 Hey, i fixed my problem with using platformio core. I also patch some package files because im using Python3.10+. Changes: ~ /home/$USER/.platformio/packages/framework-mbed/platformio/package_deps/py3/past/types/oldstr.py Line 5 :
> > ```
> > * from collections import Iterable >  from collections.abc import Iterable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ~ /home/$USER/.platformio/packages/framework-mbed/platformio/package_deps/py3/past/builtins/misc.py Line 4:
> > ```
> > * from collections import Mapping > from collections.abc import Mapping
> > ```
> 
> After these steps is it necessary any other configuration? I edited the files, however the problem persists

Hey, you can trace your stderr message and find the problem. It was enough to edit that file before but idk now.
